
export interface GameScenario {
  id: string;
  title: string;
  story?: string;
  victim?: string;
  suspects?: any[];
  evidence?: any[];
  locations?: any[];
  connections?: any[];
  connectionRules?: any[];
  solution?: any;
  initialFragment?: string;
  finalFragment?: string;
  endingMessage?: string;
  fragments?: any[];
  text?: string;
  choices?: any[];
  clues?: any[];
  temporalFragments?: any[];
  // 게임 설정 추가
  initialCards?: string[];
  winCondition?: string;
}// 임시 파일 - 빌드 오류 해결을 위한 최소한의 export


export const case5ChEn4: GameScenario = {
  "id": "shadows_of_time_chapter4_en",
  "title": "Chapter 4: Leap of Faith, New York 2122",
  "story": "Time travel to New York 2122 via a 'Leap of Faith' and have the first confrontation with Chronos.",
  "victim": "Exploration Team (potential victims)",
  "suspects": [
    {
      "id": "D01",
      "name": "Preparing for the Leap of Faith",
      "role": "Protagonist",
      "description": "Detective Lee Jin-woo's team makes final preparations for time travel.",
      "alibi": "",
      "motive": ""
    },
    {
      "id": "D10",
      "name": "The Old Man's Testimony",
      "role": "Witness",
      "description": "An old man encountered in the desolate square. Provides information about Chronos and the Great Cleansing.",
      "alibi": "",
      "motive": ""
    }
  ],
  "evidence": [
    {
      "id": "D02",
      "name": "Unfinished Time Travel Device",
      "description": "A device that will create a time tunnel by injecting the rose's energy.",
      "details": "Kim Min-jun's only hope.",
      "location": ""
    },
    {
      "id": "D03",
      "name": "Sarah's Rose (Catalyst)",
      "description": "A catalyst needed to amplify the echoes of time and create a time tunnel.",
      "details": "The rose pulsates more intensely upon insertion, distorting the surrounding air.",
      "location": ""
    },
    {
      "id": "D04",
      "name": "Time Tunnel Generation",
      "description": "A time tunnel is generated by injecting the rose's energy into the device.",
      "details": "The lab walls shimmer, and space distorts like water.",
      "location": ""
    },
    {
      "id": "D05",
      "name": "Time Tunnel Instability",
      "description": "The time tunnel is unstable, making the probability of reaching the exact destination low.",
      "details": "A one-way jump with no return.",
      "location": ""
    },
    {
      "id": "D06",
      "name": "Danger of Time Paradox",
      "description": "A warning that changing the past can unpredictably twist the present and future.",
      "details": "Chronos is already changing time.",
      "location": ""
    },
    {
      "id": "D07",
      "name": "Arrival in New York 2122",
      "description": "Arrived in future New York after successful time travel.",
      "details": "Giant holographic billboards adorn the sky, and aerial vehicles move busily.",
      "location": ""
    },
    {
      "id": "D08",
      "name": "Desolate Future New York",
      "description": "Contrary to expectations, a lifeless New York, desolate due to Chronos's intervention.",
      "details": "Everything changed due to Chronos's 'Great Cleansing'.",
      "location": ""
    },
    {
      "id": "D09",
      "name": "Giant Monument",
      "description": "A monument to forgotten heroes standing in the center of the desolate square.",
      "details": "Something is engraved in an unknown language, and countless names are meticulously inscribed.",
      "location": ""
    },
    {
      "id": "D11",
      "name": "Names of Forgotten Heroes",
      "description": "Kim Min-jun and Alistair Finch's names engraved on the monument.",
      "details": "They were 'forgotten heroes' whose history was erased by Chronos.",
      "location": "D09"
    },
    {
      "id": "D12",
      "name": "Sarah's Existence (Reconfirmed)",
      "description": "The old man's testimony reconfirms Sarah as a 'Guardian of Time'.",
      "details": "The only hope that tried to stop Chronos's plan.",
      "location": "D10"
    },
    {
      "id": "D13",
      "name": "Appearance of Chronos",
      "description": "Figures in black suits appearing above the museum.",
      "details": "They float in the air without any devices and slowly descend.",
      "location": "D07"
    },
    {
      "id": "D14",
      "name": "Chronos Agent's Suit",
      "description": "A black suit with the ability to amplify time distortion energy.",
      "details": "A small cogwheel pattern is engraved on it.",
      "location": "D13"
    },
    {
      "id": "D15",
      "name": "Time Distortion Attack",
      "description": "Chronos agents attack using time distortion energy.",
      "details": "They manipulate the flow of surrounding time to accelerate or decelerate movements.",
      "location": "D14"
    },
    {
      "id": "D16",
      "name": "Alistair Finch's Pocket Watch (Weapon)",
      "description": "A pocket watch containing the time energy of 1888 London.",
      "details": "Can overload Chronos agents' suits.",
      "location": "D03"
    },
    {
      "id": "D17",
      "name": "Chronos Agent's Weakness",
      "description": "Injecting excessive time distortion energy causes the suit to overload.",
      "details": "Can use the time energy from the pocket watch.",
      "location": "D14"
    },
    {
      "id": "D18",
      "name": "Fallen Chronos Agent",
      "description": "A normal human appearance revealed as the suit melts away.",
      "details": "Chronos were humans manipulating time.",
      "location": "D13"
    }
  ],
  "locations": [],
  "connectionRules": [
    {"id": "rule_D04", "cards": ["D02", "D03"], "result": "A time tunnel is generated through the unfinished time travel device and Sarah's rose.", "unlock": "D04"},
    {"id": "rule_D05", "cards": ["D04", "D01"], "result": "Through time tunnel generation and preparation for the leap of faith, the instability of the time tunnel is recognized.", "unlock": "D05"},
    {"id": "rule_D06", "cards": ["D05", "D01"], "result": "Through time tunnel instability and preparation for the leap of faith, the danger of a time paradox is recognized.", "unlock": "D06"},
    {"id": "rule_D07", "cards": ["D04", "D01"], "result": "Through time tunnel generation and preparation for the leap of faith, they arrive in New York 2122.", "unlock": "D07"},
    {"id": "rule_D08", "cards": ["D07", "D06"], "result": "Through arrival in New York 2122 and the danger of a time paradox, they witness the desolate future of New York.", "unlock": "D08"},
    {"id": "rule_D09", "cards": ["D08", "D07"], "result": "Through the desolate future of New York and arrival in New York 2122, a giant monument is discovered.", "unlock": "D09"},
    {"id": "rule_D10", "cards": ["D09", "D08"], "result": "Through the giant monument and the desolate future of New York, they hear the old man's testimony.", "unlock": "D10"},
    {"id": "rule_D11", "cards": ["D09", "D10"], "result": "Through the giant monument and the old man's testimony, the names of forgotten heroes are confirmed.", "unlock": "D11"},
    {"id": "rule_D12", "cards": ["D10", "D11"], "result": "Through the old man's testimony and the names of forgotten heroes, Sarah's existence as a 'Guardian of Time' is reconfirmed.", "unlock": "D12"},
    {"id": "rule_D13", "cards": ["D07", "D12"], "result": "Through arrival in New York 2122 and Sarah's existence, the appearance of Chronos is witnessed.", "unlock": "D13"},
    {"id": "rule_D14", "cards": ["D13", "D05"], "result": "Through the appearance of Chronos and time tunnel instability, the function of Chronos agents' suits is understood.", "unlock": "D14"},
    {"id": "rule_D15", "cards": ["D14", "D06"], "result": "Through Chronos agents' suits and the danger of a time paradox, their time distortion attack is understood.", "unlock": "D15"},
    {"id": "rule_D16", "cards": ["D03", "D15"], "result": "Through Sarah's rose and the time distortion attack, it is realized that Alistair Finch's pocket watch can be used as a weapon.", "unlock": "D16"},
    {"id": "rule_D17", "cards": ["D14", "D16"], "result": "Through Chronos agents' suits and Alistair Finch's pocket watch, Chronos agents' weakness is identified.", "unlock": "D17"},
    {"id": "rule_D18", "cards": ["D17", "D13"], "result": "Through Chronos agents' weakness and the appearance of Chronos, the identity of the fallen Chronos agent is confirmed.", "unlock": "D18"}
  ],
  "fragments": [],
  "winCondition": "D18",
  "initialCards": ["D01", "D02", "D03"]
}
