
// Mystery Prototype dedicated case-specific feedback system
// Provides customized feedback and hints for each case

export interface CombinationFeedback {
  cards: string[];  // Array format same as scenario
  proximity: 'close' | 'partial' | 'none';
  messages: string[];  // Messages by hint level (0,1,2 stages)
}

export interface CaseFeedbackData {
  caseId: string;
  correctSuspect: string;
  keyEvidence: string[];
  combinationFeedback: CombinationFeedback[];  // Changed to array-based
  urgentHints: string[];
  contextualHints: string[];
}

// Case 1: Mansion Murder Case Feedback Data
const case5FeedbackDataEn6: CaseFeedbackData = {
  "caseId": "shadows_of_time_chapter6_en",
  "correctSuspect": "F04",
  "keyEvidence": ["F04", "F06", "F07", "F11"],
  "combinationFeedback": [
    {
      "cards": ["F04", "F06"],
      "proximity": "close",
      "messages": [
        "'Temporal Anchor' sequence and time tunnel generation. The core process of time travel.",
        "The time tunnel was generated by connecting the rose's energy to the unfinished device.",
        "💡 Now you must overcome the instability of the time tunnel and reach the exact destination."
      ]
    },
    {
      "cards": ["F08", "F11"],
      "proximity": "close",
      "messages": [
        "Arrival in New York 2122 and detection of Chronos's appearance. This future is different from what was expected.",
        "Chronos has appeared to eliminate Sarah. You must identify their location.",
        "💡 You must analyze Chronos's time distortion patterns to find their weakness."
      ]
    },
    {
      "cards": ["F01", "F02"],
      "proximity": "partial",
      "messages": [
        "Time Rewind theory and Sarah's Rose. The theoretical background and core catalyst for time travel.",
        "📖 This rose is amplifying the echoes of time due to its strong emotional connection to Sarah.",
        "💭 You need to consider how to use this energy to reverse the flow of time."
      ]
    },
    {
      "cards": ["F03", "F05"],
      "proximity": "none",
      "messages": [
        "Unfinished time travel device and lecture venue and time. A tool and a goal.",
        "🔍 The device itself is important, but you must focus on the 'energy' and 'catalyst' that power it.",
        "💭 You need to consider how to utilize the rose's energy and how to stabilize the time tunnel."
      ]
    }
  ],
  "urgentHints": [
    "🚨 Urgent Tip: A subtle time distortion energy is continuously emitted from Chronos agents' suits.",
    "🚨 Scene Evidence: The time distortion phenomenon detected above the museum has a specific pattern.",
    "🚨 Future Information: Sarah's lecture will be a crucial turning point that changes the future of humanity."
  ],
  "contextualHints": [
    "💡 Deduction Tip: In time travel, precise movement to the correct time and place is crucial.",
    "💡 Investigation Perspective: Why would Chronos try to stop Sarah's lecture? What is their ultimate goal?",
    "💡 Survival Strategy: The time tunnel's instability is dangerous. All actions must be swift."
  ]
}

// Case 3 dedicated feedback data - for independent use
export default case5FeedbackDataEn6;